Id: LutzRoeder.Netron
Version: 4.3.3
Name: Netron
Publisher: Lutz Roeder
AppMoniker: netron
Description: Visualizer for neural network, deep learning and machine learning models
License: Copyright (c) Lutz Roeder
Homepage: https://github.com/lutzroeder/netron
Installers:
  - Arch: x86
    InstallerType: nullsoft
    Url: https://github.com/lutzroeder/netron/releases/download/v4.3.3/Netron-Setup-4.3.3.exe
    Sha256: A9D62F859509C1D404D04F21E2D13FAB65444F731E9CC42547827F6FD589C564